"""users table

Revision ID: 80d7f0f7af7e
Revises: 
Create Date: 2026-05-05 08:46:55.844259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d7f0f7af7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orgonization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('Contact_email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orgonization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orgonization_Contact_email'), ['Contact_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_orgonization_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_orgonization_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('orgonization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orgonization_name'))
        batch_op.drop_index(batch_op.f('ix_orgonization_description'))
        batch_op.drop_index(batch_op.f('ix_orgonization_Contact_email'))

    op.drop_table('orgonization')
    op.drop_table('alert')
    # ### end Alembic commands ###
